[project]
name = "cam-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamed-faaris", email = "mohamedfaaris.dev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "opencv-contrib-python>=5.0.0.93",
    "opencv-python>=5.0.0.93",
    "pyrealsense2>=2.58.4.10922",
    "pytesseract>=0.3.13",
    "ultralytics>=8.4.166",
]

[project.scripts]
cam-test = "cam_test:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
